name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures a full clone for proper push operations

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote add space https://fmcsihe2929:${HF_TOKEN}@huggingface.co/spaces/fmcsihe2929/FernandoMartinezMarco_HarborSentinel
          git push --force space main